### ISSUE TITLE
Consider creating a table of contents for the alphabet for easier navigation?

### ISSUE THREAD

**Issue by erictleung** [rstudio-education/glossRy#9]
This list could get long, so having a quick table of contents of all the letters of the alphabet may make it easier to navigate.

Something like

```
**Contents**

- [A](#A)
- [B](#B)
...
```

to render as 

**Contents**

- [A](#A)
- [B](#B)

And throughout the glossRy itself, have heading markers of `# A` and so on to divide the words up. 

This requires a large change, so just want to put it out there for discussion.

**Comment by gvwilson** [comment]
Closed in b5e3603
